# A full list of config variables is available at:
# https://supabase.com/docs/guides/hosting/platform/self-hosting

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["https://localhost:8081"]
jwt_expiry = 3600
enable_refresh_token_rotation = false

[functions.automation-api]
verify_jwt = false

[functions.radar-api]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.sync-social-data]
verify_jwt = false

[functions.sync-messaging-channels]
verify_jwt = false

[functions.collect-social-analytics]
verify_jwt = false

[functions.publish-post]
verify_jwt = false

[functions.sync-telegram-info]
verify_jwt = false

[functions.proxy-media]
enabled = true
verify_jwt = false
import_map = "./functions/proxy-media/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/proxy-media/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/proxy-media/*.html" ]
