import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";
import fs from "fs";
import https from "https";
import http from "http";
import { componentTagger } from "lovable-tagger";

/**
 * Plugin: Gera public/config.js a partir do .env no momento do build.
 * Garante que as páginas OAuth callback sempre leiam a URL correta.
 */
function generateConfigPlugin() {
  return {
    name: "generate-config-js",
    buildStart() {
      const env = loadEnv("production", process.cwd(), "");
      const url = env.SUPABASE_URL || env.VITE_SUPABASE_URL || "https://supabase.webradiovitoria.com.br";
      const key = env.SUPABASE_ANON_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY || "";
      const content = `/**
 * AUTO-GENERATED by vite.config.ts — DO NOT EDIT MANUALLY.
 * Source: .env → SUPABASE_URL / SUPABASE_ANON_KEY
 * Regenerate: npx vite build
 */
window.__SUPABASE_CONFIG__ = {
  SUPABASE_URL: ${JSON.stringify(url)},
  SUPABASE_ANON_KEY: ${JSON.stringify(key)},
};
`;
      fs.writeFileSync(path.resolve(__dirname, "public", "config.js"), content, "utf-8");
      console.log(`[config.js] Generated with SUPABASE_URL=${url}`);
    },
  };
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  // ─── CENTRALIZED URL ────────────────────────────────────────────────
  // All sources converge to ONE variable. Change .env → everything updates.
  const supabaseUrl = env.SUPABASE_URL || env.VITE_SUPABASE_URL || 'https://supabase.webradiovitoria.com.br';
  const supabaseAnonKey = env.SUPABASE_ANON_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

  const proxyAgent = new (supabaseUrl.startsWith('http:') ? http : https).Agent({
    keepAlive: true,
    family: 4,
    timeout: 30000,
  });

  return {
    // ─── Define: inject variables into client code ─────────────────────
    // import.meta.env.VITE_SUPABASE_URL works everywhere in React code
    define: {
      'import.meta.env.VITE_SUPABASE_URL': JSON.stringify(supabaseUrl),
      'import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY': JSON.stringify(supabaseAnonKey),
    },

    server: {
      host: true,
      port: 8081,
      strictPort: true,
      hmr: {
        overlay: false,
      },
      headers: {
        'Cross-Origin-Opener-Policy': 'same-origin',
        'Cross-Origin-Embedder-Policy': 'credentialless',
      },
      proxy: {
        '/api': {
          target: 'http://localhost:3001',
          changeOrigin: true,
        },
        '/supabase': {
          target: supabaseUrl,
          changeOrigin: true,
          secure: false,
          ws: true,
          agent: proxyAgent,
          timeout: 180000,
          proxyTimeout: 180000,
          rewrite: (path) => path.replace(/^\/supabase/, ''),
          configure: (proxy) => {
            proxy.on('proxyReq', (proxyReq, req) => {
              proxyReq.setHeader('origin', supabaseUrl);
              proxyReq.removeHeader('referer');

              if (req.url && req.url.includes('/storage/v1/object/')) {
                proxyReq.removeHeader('accept-encoding');
              }
            });
            proxy.on('proxyReqWs', (proxyReq) => {
              proxyReq.setHeader('origin', supabaseUrl);
              proxyReq.removeHeader('referer');
            });
            proxy.on('proxyRes', (proxyRes, req) => {
              if (req.url && req.url.includes('/storage/v1/object/')) {
                delete proxyRes.headers['content-encoding'];
              }
            });
          },
        },
      },
    },
    optimizeDeps: {
      include: [
        "react",
        "react-dom",
        "react-dom/client",
        "react/jsx-dev-runtime",
        "react/jsx-runtime",
        "react-router-dom",
        "@tanstack/react-query",
        "@supabase/supabase-js",
        "lucide-react",
        "@radix-ui/react-accordion",
        "@radix-ui/react-alert-dialog",
        "@radix-ui/react-aspect-ratio",
        "@radix-ui/react-avatar",
        "@radix-ui/react-checkbox",
        "@radix-ui/react-collapsible",
        "@radix-ui/react-context-menu",
        "@radix-ui/react-dialog",
        "@radix-ui/react-dropdown-menu",
        "@radix-ui/react-hover-card",
        "@radix-ui/react-label",
        "@radix-ui/react-menubar",
        "@radix-ui/react-navigation-menu",
        "@radix-ui/react-popover",
        "@radix-ui/react-progress",
        "@radix-ui/react-radio-group",
        "@radix-ui/react-scroll-area",
        "@radix-ui/react-select",
        "@radix-ui/react-separator",
        "@radix-ui/react-slider",
        "@radix-ui/react-slot",
        "@radix-ui/react-switch",
        "@radix-ui/react-tabs",
        "@radix-ui/react-toast",
        "@radix-ui/react-toggle",
        "@radix-ui/react-toggle-group",
        "@radix-ui/react-tooltip",
        "react-avatar-editor",
        "framer-motion",
        "clsx",
        "tailwind-merge",
        "class-variance-authority",
        "date-fns",
        "date-fns/locale",
        "cmdk",
        "embla-carousel-react",
        "input-otp",
        "next-themes",
        "sonner",
        "vaul",
        "zustand",
      ],
      exclude: [
        "@imgly/background-removal",
      ],
    },
    plugins: [
      react(),
      mode === "development" && componentTagger(),
      generateConfigPlugin(),
    ].filter(Boolean),
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "./src"),
      },
    },
    build: {
      rollupOptions: {
        output: {
          manualChunks(id: string) {
            if (id.includes('node_modules/react-dom') || id.includes('node_modules/react/') || id.includes('node_modules/react-router')) return 'vendor-react';
            if (id.includes('node_modules/@radix-ui/')) return 'vendor-ui';
            if (id.includes('node_modules/framer-motion')) return 'vendor-motion';
            if (id.includes('node_modules/@supabase/')) return 'vendor-supabase';
            if (id.includes('node_modules/recharts')) return 'vendor-charts';
          },
        },
      },
      chunkSizeWarningLimit: 600,
      cssCodeSplit: true,
      sourcemap: false,
    },
  };
});
