// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const fetchWithTimeout: typeof fetch = (url, options) => {
  if (typeof url === 'string' && url.includes('/functions/v1/')) {
    return fetch(url, options);
  }
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(new DOMException('Timeout', 'TimeoutError')), 60000);
  return fetch(url, { ...options, signal: controller.signal })
    .finally(() => clearTimeout(timeout));
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: fetchWithTimeout },
});

export const SUPABASE_ANON_KEY = SUPABASE_PUBLISHABLE_KEY;
export const SUPABASE_PROJECT_URL = SUPABASE_URL;

export function clearSupabaseSession(): void {
  const AUTH_STORAGE_KEY = `sb-${SUPABASE_URL.replace(/[^a-zA-Z0-9]/g, '-')}-auth-token`;
  try { localStorage.removeItem(AUTH_STORAGE_KEY); } catch {}
}