// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { localDb } from './local-client';

const SUPABASE_URL = import.meta.env.DEV
  ? `${window.location.origin}/supabase`
  : import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const USE_LOCAL = import.meta.env.VITE_USE_LOCAL_DB === 'true' || import.meta.env.USE_LOCAL_DB === 'true';

function isNetworkAbortError(err: any): boolean {
  if (!err) return false;
  const msg = err.message || String(err);
  return (
    msg.includes('AbortError') ||
    msg.includes('signal is aborted') ||
    msg.includes('TimeoutError') ||
    msg.includes('Failed to fetch') ||
    msg.includes('NetworkError')
  );
}

const EDGE_FUNCTION_TIMEOUT_MS = 90000;
const REGULAR_TIMEOUT_MS = 45000;

const fetchWithTimeout: typeof fetch = (url, options) => {
  const controller = new AbortController();
  const isEdgeFunction = typeof url === 'string' && url.includes('/functions/v1/');
  const timeoutMs = isEdgeFunction ? EDGE_FUNCTION_TIMEOUT_MS : REGULAR_TIMEOUT_MS;
  const timeout = setTimeout(() => controller.abort(new DOMException('Timeout', 'TimeoutError')), timeoutMs);
  
  const fetchOptions = { ...options, signal: controller.signal };
  
  return fetch(url, fetchOptions)
    .catch((err) => {
      if (isNetworkAbortError(err)) {
        const enhancedErr = new Error(err.message);
        (enhancedErr as any).isNetworkAbort = true;
        (enhancedErr as any).originalError = err;
        throw enhancedErr;
      }
      throw err;
    })
    .finally(() => clearTimeout(timeout));
};

const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: fetchWithTimeout },
});

export const supabase = USE_LOCAL ? localDb : supabaseClient;

// Base URL for Edge Function invocations. In local mode points at our Express
// "functions" runtime; otherwise at the Supabase project.
export const getFunctionsBase = () =>
  USE_LOCAL ? "/api/functions" : `${import.meta.env.VITE_SUPABASE_URL}/functions/v1`;

export const SUPABASE_ANON_KEY = SUPABASE_PUBLISHABLE_KEY;
export const SUPABASE_PROJECT_URL = SUPABASE_URL;

const AUTH_STORAGE_KEY = `sb-${SUPABASE_URL.replace(/[^a-zA-Z0-9]/g, '-')}-auth-token`;

export function clearSupabaseSession(): void {
  try { localStorage.removeItem(AUTH_STORAGE_KEY); } catch {}
}

function clearStaleSession(): void {
  try {
    const raw = localStorage.getItem(AUTH_STORAGE_KEY);
    if (!raw) return;
    const parsed = JSON.parse(raw);
    if (parsed?.expires_at && Date.now() > parsed.expires_at * 1000 + 3600000) {
      clearSupabaseSession();
    }
  } catch {
    clearSupabaseSession();
  }
}

clearStaleSession();
